"""Select top features per theme from a classification results pickle."""

from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import pandas as pd

from src.classification.shap_heuristic import select_features


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        argparse.Namespace: Parsed CLI arguments.
    """
    parser = argparse.ArgumentParser(
        description="Select top features per theme from a CLI results pickle.",
    )
    parser.add_argument(
        "--input-pkl",
        type=Path,
        required=True,
        help="Path to results.pkl generated by src/classify.py.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Optional CSV output path for selected features.",
    )
    return parser.parse_args()


def main() -> None:
    """Run feature selection from a results pickle.

    Returns:
        None: Writes CSV output or prints to stdout.
    """
    args = parse_args()

    if not args.input_pkl.exists():
        raise FileNotFoundError(f"Input pickle not found: {args.input_pkl}")

    with args.input_pkl.open("rb") as f:
        results = pickle.load(f)

    shap_scores = results.get("shap_scores", {})
    if not shap_scores:
        raise ValueError("No 'shap_scores' found in the pickle file.")

    rows = []
    for theme, score_df in shap_scores.items():
        if score_df is None or len(score_df) == 0:
            continue
        feat_ids = select_features(score_df["final_shap_score"]).index
        feats = score_df["feature"].loc[feat_ids]
        for feat in feats.tolist():
            rows.append({"theme": theme, "feature": feat})

    if not rows:
        raise ValueError("No features selected. Check the input pickle contents.")

    out_df = pd.DataFrame(rows)

    if args.output_csv is not None:
        args.output_csv.parent.mkdir(parents=True, exist_ok=True)
        out_df.to_csv(args.output_csv, index=False)
    else:
        print(out_df.to_string(index=False))


if __name__ == "__main__":
    main()
